### ISSUE TITLE
Error when generating JSON

### ISSUE THREAD

**Issue by bergel** [dorellang/hunter#7]
I got the following error:

```
  esprima-bin-wrapper git:(master) ✗ node esprima-bin-wrapper.js -m /Users/alexandrebergel/Desktop/Hunter/g6 > g6.json
/Users/alexandrebergel/Desktop/Hunter/esprima-bin-wrapper/esprima-bin-wrapper.js:141
console.log(JSON.stringify(results, undefined, 2));
                 ^

RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at Object.<anonymous> (/Users/alexandrebergel/Desktop/Hunter/esprima-bin-wrapper/esprima-bin-wrapper.js:141:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
```

[g6.zip](https://github.com/dorellang/hunter/files/2119862/g6.zip)

**Comment by dorellang** [comment]
This commit https://github.com/dorellang/esprima-bin-wrapper/commit/e44e1c941b5dd858db0485d6d9a4198e9d5e80aa should take care of this
